### ISSUE TITLE
Set up bucket list backend

### ISSUE THREAD

**Issue by Kriordan** [Kriordan/personal_portfolio#6]
#### Description
I'd like to add a bucket list page at the endpoint `/bucket` where I show a collection of things I'd like to do in my life. I'd like for the things in the list to visually indicate whether they have been completed (i.e. strikethrough or checkmark). It should include all CRUD methods and be attached to the db.

For this issue, build out the BucketListItem model and endpoint which returns a list of all BucketListItem objects in db in JSON.

#### Files
For the new endpoint:
https://github.com/Kriordan/personal_portfolio/blob/master/project/foyer/views.py

For the BucketListItem model:
https://github.com/Kriordan/personal_portfolio/blob/master/project/models.py

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Create endpoint `/bucket`
- [ ] Set up BucketListItem model
- [ ] Return list of BucketListItem objects from GET `/bucket`
